apiVersion: v1
kind: Service
metadata:
  name: board-backend-service
  namespace: board-app
spec:
  type: ClusterIP
  selector:
    app: board-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
